name: Figure-Chan Client CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "figure-chan-client/**"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Example-Step
        run: echo "Hello World!"
